### ISSUE TITLE
Add -M90% param to git diff

### ISSUE THREAD

**Issue by isitnikov** [katmoon/create-patch#1]
Could you please add -M90% into https://github.com/katmoon/create-patch/blob/3d4ac7e4963a04ee6b1827cc9e60b14ab308e822/create-patch.sh#L200

according to documentation: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt--Mltngt

> -M[<n>]
> --find-renames[=<n>]
> Detect renames. If n is specified, it is a threshold on the similarity index (i.e. amount of addition/deletions compared to the file’s size). For example, -M90% means Git should consider a delete/add pair to be a rename if more than 90% of the file hasn’t changed. Without a % sign, the number is to be read as a fraction, with a decimal point before it. I.e., -M5 becomes 0.5, and is thus the same as -M50%. Similarly, -M05 is the same as -M5%. To limit detection to exact renames, use -M100%. The default similarity index is 50%.

With this option, renaming mechanism in patch will work like full file delete then create, instead of using "rename from ... rename to .." construction.

Such patch will be applicable on Adobe Commerce Cloud correctly and renaming **diff --git** to **diff -Nuar** will not cause issues (see https://github.com/magento/magento-cloud-patches/blob/bdb763c75a3c11f30217e44e69863035504e57a1/src/Patch/Applier.php#L195)

**Comment by katmoon** [comment]
Hi @isitnikov 
Thank you for reporting your issue. It's resolved now. 
We appreciate your dedication to enhancing the overall quality of our product.
